Validate enumerations.
mouse07410/asn1c pull request #121
Opened 2023-03-10 05:58 UTC by bknotwell

I'm not a fan of the way I threaded state through with the _localvalidation_ member but I don't have a better idea.  I added it as a union to make it easier to reuse it for other use cases.

2023-03-10 06:03 UTC, bknotwell commented
I considered adding a way to turn this off as working validation might surprise people but decided against it.

2023-03-11 23:44 UTC, mouse07410 commented
@bknotwell could you please take a look at why the CI fails, and (hopefully) remedy it? Thanks!

2023-03-30 12:13 UTC, mouse07410 commented
@bknotwell ping?

2023-05-01 12:46 UTC, mouse07410 commented
@bknotwell thank you for the contribution - but are you planning to fix the CI failures?

2023-06-15 23:49 UTC, mouse07410 commented
> I considered adding a way to turn this off as working validation might surprise people but decided against it.

@bknotwell i can't afford merging a PR that breaks validation. Could you fix it, please?

2025-03-06 02:41 UTC, mouse07410 commented
We need to re-activate CI and get a clean run, somehow.

2025-03-07 00:21 UTC, mouse07410 requested changes
Current PR keeps failing CI. asn1c build with it, but fails tests.
Please help fixing it.

2025-09-10 01:43 UTC, mouse07410 commented
@copilot no merging until all CI runs pass

2025-09-10 01:54 UTC, mouse07410 commented
@copilot run CI over this PR

2025-09-17 23:06 UTC, mouse07410 commented on libasn1compiler/asn1c_C.c
> +			} else
@copilot replace magic numbers boolean. Update this PR

2025-09-18 00:34 UTC, mouse07410 commented
@copilot update this PR

2025-09-21 08:21 UTC, mouse07410 commented
@bknotwell it looks like enumerations are already validated correctly. Please let me know if it is not the case.

2025-09-21 08:21 UTC, closed without merging