Add version and origin URL to binary and generated sources
mouse07410/asn1c pull request #131
Opened 2023-06-02 16:30 UTC by gatopeich

asn1c identifies itself and its generated sources with the latest release/tag name, commit hash, and date of the last commit.
Also shows the URL from `git remote get-url origin` so it is easy to trace it back to the specific fork that was used.
```
$ asn1c -v
ASN.1 Compiler, v2023.5-0-g47a234a0-dirty-2023-05-18 from https://github.com/mouse07410/asn1c
Copyright (c) 2003-2017 Lev Walkin <vlm@lionet.info> and contributors.
```

And in the C sources:
```c
/*
 * Generated by asn1c-v2023.5-0-g47a234a0-dirty-2023-05-18 from https://github.com/mouse07410/asn1c
 * From ASN.1 module "F1AP-Containers"
 * 	found in "f1ap-v15.10.asn"
 */
```

2023-06-02 16:32 UTC, gatopeich commented
@mouse07410 this is my first PR, let's start by distinguishing the version we are using... should adjust automatically for any fork cloned via git.
Afterwards we'll look into more interesing fixes...

2023-06-15 17:22 UTC, mouse07410 commented
> @mouse07410 this is my first PR,

Certainly. First, welcome in! 

> let's start by distinguishing the version we are using... should adjust automatically for any fork cloned via git. 

Yes. My apologies for delay in getting to this - other things piled up.

Let's see what the CI has to say. I suspect we (you ;-) would need to do more changes, as I seem to recall that ASN.1 compiler version is hard-coded in the tests (rather unfortunate, but I "inherited" this vast body of tests from the upstream).

> 

> Afterwards we'll look into more interesting fixes...

Absolutely!

2023-08-05 01:30 UTC, mouse07410 commented
@gatopeich could you please try to address the CI failure in your PR?

2023-08-27 00:32 UTC, gatopeich commented
I haven't forgotten, will do it on next chance

2023-10-12 07:27 UTC, v0-e commented
Hey guys. I agree, this is a very useful feature.
In my system, with a freshly cloned repo (from gatopeich:o-ran), the version command outputs:
```
$ asn1c -v
ASN.1 Compiler, v18f84280-2023-05-18 from https://github.com/gatopeich/asn1c
Copyright (c) 2003-2017 Lev Walkin <vlm@lionet.info> and contributors.
```
I suggest keeping some sort of incremental versioning (like SemVer), as package systems usually rely on an incremental system to correctly do updates.

2023-10-12 10:44 UTC, mouse07410 commented
Standing by for a PR that provides the necessary functionality and passes CI. 😉

2024-12-02 14:26 UTC, mouse07410 commented
Standing by for updates to this PR that resolves conflicts and passes CI.

2025-02-20 08:57 UTC, gatopeich commented
I hear you 🙂

2025-09-07 09:50 UTC, gatopeich commented
@mouse07410 let's see if Copilot suggestions fix this PR...

2025-09-07 13:12 UTC, mouse07410 commented
My concern is that apparently something of the `asn1c` version info is hard-coded into gazillions of tests. And I don't have time or patience to hand-fix each and every one of them. 

Indeed, let's see if Copilot does that.

2025-09-07 15:35 UTC, mouse07410 requested changes
Besides these changes, all the tests need to be verified and corrected.

2025-09-07 17:59 UTC, gatopeich commented
No luck

2025-09-10 01:40 UTC, mouse07410 commented
@copilot debug and fix CI errors

2025-09-12 01:10 UTC, mouse07410 commented
@copilot find the problem with C/C++ CI for this PR. Determine why CI fails and fix it.

2025-09-17 21:31 UTC, mouse07410 commented
OK, I seem unable to fix this easily and correctly. Copilot doesn't seem to either. I'll wait until somebody come up who can.

2025-10-06 06:14 UTC, gatopeich commented
The test failures in CI occurred likely because this PR updates the version string, which is included in the outputs compared by the test suite.
According to Copilot, we shall regenerate the reference outputs using:

```sh
cd tests/tests-asn1c-compiler
./check-parsing.sh regenerate
```

And commit the updated *.asn1.+* files. This aligns the expected outputs with the new version and resolves the CI failures due to output mismatches.

@copilot, can you implement this fix?

2025-11-07 17:34 UTC, gatopeich commented
@mouse07410 I fixed it after all

2025-11-07 22:20 UTC, gatopeich commented
I avoided touching the reference files by replacing new version strings with old ones with sed on the test outputs.
This way we pass tests without messing with them.

2025-11-11 00:45 UTC, mouse07410 commented
> I avoided touching the reference files by replacing new version strings with old ones with sed on the test outputs. This way we pass tests without messing with them.

Wonderful! Can I ask you to rebase against the current `vlm_master`?

2025-11-11 01:04 UTC, mouse07410 requested changes
I'm still getting errors:

```text
Checking ../../tests/tests-asn1c-compiler/125-bitstring-constraint-OK.asn1 against ../../tests/tests-asn1c-compiler/125-bitstring-constraint-OK.asn1.+-X
--- .tmp.check-parsing.80852.old        2025-11-10 19:59:10
+++ .tmp.check-parsing.80852.new        2025-11-10 19:59:10
@@ -1,4 +1,4 @@
-<!-- XML DTD generated by  -->
+<!-- XML DTD generated by  e5cdd5fd-2025-11-10 -->
 
 <!-- ASN.1 module
 ModuleBitStringConstraint { iso org(3) dod(6) internet(1) private(4)
.  .  .
Checking ../../tests/tests-asn1c-compiler/138-oer-constraints-OK.asn1 against ../../tests/tests-asn1c-compiler/138-oer-constraints-OK.asn1.+-P_-gen-OER
Generated asn_constant.h
--- .tmp.check-parsing.80852.old        2025-11-10 19:59:10
+++ .tmp.check-parsing.80852.new        2025-11-10 19:59:10
@@ -1841,7 +1841,7 @@
 /*** <<< asn_constant.h >>> ***/
 
 /*
- * Generated by 
+ * Generated by  e5cdd5fd-2025-11-10 (https://github.com/mouse07410/asn1c)
  */
 
 #ifndef _ASN_CONSTANT_H
.  .  .
Checking ../../tests/tests-asn1c-compiler/139-component-relation-OK.asn1 against ../../tests/tests-asn1c-compiler/139-component-relation-OK.asn1.+-P
Generated asn_constant.h
--- .tmp.check-parsing.80852.old        2025-11-10 19:59:11
+++ .tmp.check-parsing.80852.new        2025-11-10 19:59:11
@@ -693,7 +693,7 @@
 /*** <<< asn_constant.h >>> ***/
 
 /*
- * Generated by 
+ * Generated by  e5cdd5fd-2025-11-10 (https://github.com/mouse07410/asn1c)
  */
 
 #ifndef _ASN_CONSTANT_H
.  .  .
Checking ../../tests/tests-asn1c-compiler/140-component-relation-OK.asn1 against ../../tests/tests-asn1c-compiler/140-component-relation-OK.asn1.+-P
Generated asn_constant.h
--- .tmp.check-parsing.80852.old        2025-11-10 19:59:11
+++ .tmp.check-parsing.80852.new        2025-11-10 19:59:11
@@ -693,7 +693,7 @@
 /*** <<< asn_constant.h >>> ***/
 
 /*
- * Generated by 
+ * Generated by  e5cdd5fd-2025-11-10 (https://github.com/mouse07410/asn1c)
  */
 
 #ifndef _ASN_CONSTANT_H
.  .  .
Checking ../../tests/tests-asn1c-compiler/98-attribute-class-OK.asn1 against ../../tests/tests-asn1c-compiler/98-attribute-class-OK.asn1.+-P
FATAL: Inappropriate value {3 2 1} for type raf
FATAL: Inappropriate value {3 2 2} for type rcf
```

2025-11-11 01:04 UTC, mouse07410 commented on configure.ac
> +    echo -n "https://github.com/vlm/asn1c/issues"
You want bug reports to go to the upstream repo? Or is it for the cases when the script can't determine if it's our clone or not?

2025-11-11 01:07 UTC, mouse07410 commented
@gatopeich  I don't know why GitHub CI passes, and my local - doesn't. I still suggest rebasing your PR against the current `vlm_master`. In the meanwhile, I'll try to dig into this on my side too.

2025-11-11 07:13 UTC, gatopeich commented on configure.ac
> +    echo -n "https://github.com/vlm/asn1c/issues"
Nope, this looks like Copilot over-exceeding its coding capacity.
Let me clean up and leave your repo as default URL since it is the best maintained IMO...

2025-11-11 07:39 UTC, gatopeich commented on configure.ac
> +    echo -n "https://github.com/vlm/asn1c/issues"
I am applying a fix here anyway...

2025-11-11 11:46 UTC, gatopeich commented
> @gatopeich I don't know why GitHub CI passes, and my local - doesn't. I still suggest rebasing your PR against the current `vlm_master`. In the meanwhile, I'll try to dig into this on my side too.

It was rebased already. Can you try again?

2025-11-11 21:12 UTC, mouse07410 commented
@gatopeich do you have any idea why I am seeing this:
<img width="702" height="439" alt="Screenshot 2025-11-11 at 16 11 51" src="https://github.com/user-attachments/assets/cbc9aca8-6890-457c-ba7d-e6cdc130cfdc" />

What kind of conflicts is it talking about?

2025-11-11 21:14 UTC, gatopeich commented
> Hey guys. I agree, this is a very useful feature. In my system, with a freshly cloned repo (from gatopeich:o-ran), the version command outputs:
> 
> ```
> $ asn1c -v
> ASN.1 Compiler, v18f84280-2023-05-18 from https://github.com/gatopeich/asn1c
> Copyright (c) 2003-2017 Lev Walkin <vlm@lionet.info> and contributors.
> ```
> 
> I suggest keeping some sort of incremental versioning (like SemVer), as package systems usually rely on an incremental system to correctly do updates.

In order to get an incremental version we just have to declare releases with tag "v1.2.3". Then the version will be picked by git from the tag.

2025-11-11 21:16 UTC, gatopeich commented
@mouse07410 there is no conflict now apparently...

2025-11-11 21:30 UTC, mouse07410 commented
> What kind of conflicts is it talking about?

@gatopeich that's what I would like to know. :-(

2025-11-11 21:40 UTC, gatopeich commented
Wow this CI build is taking ages. On my laptop with make -j it took only a few minutes.

2025-11-11 22:48 UTC, mouse07410 approved these changes

2025-11-11 22:49 UTC, merged

2025-11-12 09:43 UTC, gatopeich commented
Awesomely now we will be able to know which compiler was used to compile ASN1c files!

2025-11-12 09:45 UTC, gatopeich commented
@mouse07410 time to make a versioned release?